pipeline:
  name: Build ci-cd
  identifier: Build_v3cnaSbk_ci_cd_1764148395175
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Build Go app
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: |-
                      go mod init ci-cd
                      go build
                      go test
          platform:
            os: MacOS
            arch: Arm64
          runtime:
            type: Docker
            spec: {}
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: Deploy
          environment:
            environmentRef: Test
            deployToAll: false
            infrastructureDefinitions:
              - identifier: Test
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  properties:
    ci:
      codebase:
        connectorRef: account.Github
        repoName: v3cnaSbk/ci-cd
        build: <+input>
